CREATE TABLE Usuario
(
    ID_USUARIO    VARCHAR(36) PRIMARY KEY,
    LOGIN         VARCHAR(255),
    SENHA         VARCHAR(255),
    NOME_COMPLETO VARCHAR(255),
    EMAIL         VARCHAR(255),
    ID_PERFIL     BIGINT,
    FOREIGN KEY (ID_PERFIL) REFERENCES Perfil (ID_PERFIL)
);
