CREATE TABLE Usuario
(
    ID_USUARIO    VARCHAR(36) PRIMARY KEY  NOT NULL,
    LOGIN         VARCHAR(255) NOT NULL,
    SENHA         VARCHAR(255) NOT NULL,
    NOME_COMPLETO VARCHAR(255) NOT NULL,
    EMAIL         VARCHAR(255) NOT NULL,
    ID_PERFIL     BIGINT,
    FOREIGN KEY (ID_PERFIL) REFERENCES Perfil (ID_PERFIL)
);
