CREATE TABLE Endereco
(
    ID_USUARIO VARCHAR(36) PRIMARY KEY NOT NULL,
    RUA        VARCHAR(255) NOT NULL,
    BAIRRO     VARCHAR(255) NOT NULL,
    CIDADE     VARCHAR(255) NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES Usuario (ID_USUARIO)
);
