CREATE TABLE Endereco
(
    ID_USUARIO VARCHAR(36) PRIMARY KEY,
    RUA        VARCHAR(255),
    BAIRRO     VARCHAR(255),
    CIDADE     VARCHAR(255),
    FOREIGN KEY (ID_USUARIO) REFERENCES Usuario (ID_USUARIO)
);
